save/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('users.urls')),
    path('', include('saveNow.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

saveNow/urls.py
from django.urls import path, include
from . import views

app_name = 'saveNow'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('create', views.createPost, name = 'create'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('signup', views.signup_user, name = 'signup'),
    path('login', views.login_user, name = 'login'),
    path('logout', views.logout_user, name = 'logout'),
]

saveNow/models.py
from django.db import models
from django.contrib.auth.models import User

class SavePost(models.Model):
    rank = models.CharField(max_length=20)
    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length = 20)
    email = models.EmailField()
    address = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.f_name

users/models.py
from django.db import models

# Create your models here.

saveNow/forms.py
from django import forms
from . import models

class CreateSavePost(forms.ModelForm):
    rank = forms.CharField(max_length= 50, widget = forms.TextInput(attrs= {'type':'text', 'placeholder':'Rank'}) )
    f_name = forms.CharField(max_length = 20, widget = forms.TextInput(attrs= {'type':'text', 'placeholder':'First Name'}) )
    l_name = forms.CharField(max_length = 20, widget = forms.TextInput(attrs= {'type':'text', 'placeholder':'Last Name'}) )
    address = forms.Field(widget = forms.TextInput(attrs= {'type':'text', 'placeholder':'Address Information'}))
    thumb = forms.ImageField(widget = forms.FileInput())


    class Meta:
        model = models.SavePost
        fields = ['rank','f_name','l_name', 'address','thumb']

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget = forms.TextInput(attrs = {'type':'text', 'placeholder':'Username'}) )
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'type':'password', 'placeholder':'Password'}))

class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget = forms.EmailInput(attrs= {'type':'email', 'name':'email', 'placeholder':'Email'}))
    f_name = forms.CharField(max_length = 20, widget = forms.TextInput(attrs= {'type':'text',  'placeholder':'First Name'}) )
    l_name = forms.CharField(max_length = 20, widget = forms.TextInput(attrs= {'type':'text', 'placeholder':'Last Name'}) )
    username = forms.CharField(widget = forms.TextInput(attrs = {'type':'text', 'placeholder':'Username'}) )
    password1 = forms.CharField(widget = forms.PasswordInput(attrs = {'type':'password', 'placeholder':'Password'}))
    password2 = forms.CharField(widget = forms.PasswordInput(attrs = {'type':'password', 'placeholder':'Retype Password'}))
    class Meta:
        model = User
        fields = ('username','f_name','l_name','email','password1','password2')


    def save(self,commit = True):
        user = super(SignUpForm,self).save(commit=False)
        user.f_name = self.cleaned_data['f_name']
        user.l_name = self.cleaned_data['l_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

saveNow/views.py
from django.shortcuts import render, redirect
from . models import SavePost
from django.contrib.auth.decorators import login_required
from . import forms

def index(request):
    savepost = SavePost.objects.all().order_by('date')
    return render (request, 'saveNow/index.html', {'savepost':savepost})

@login_required(login_url='users/login')
def createPost(request):
    if request.method == 'POST':
        form = forms.CreateSavePost(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('saveNow:index')
    else:
        form = forms.CreateSavePost()
    return render(request, 'saveNow/savepost.html',{'form':form})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout
from . import forms
from users.forms import LoginForm, SignUpForm
from django.contrib.auth.forms import UserCreationForm

def signup_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('saveNow:index')
    else:
        form = SignUpForm()
    return render(request,'users/signup.html', {'form':form})

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('saveNow:index')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form':form})

def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('saveNow:index')

saveNow/templates/saveNow/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Save Now</title>
    <link rel="stylesheet" type="text/css" href="{% static 'saveNow/Bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'saveNow/style.css' %}">
    
</head>
<body>
        <div class="row">
                <div class=nav>
                        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navpadding">
                                <a class="navbar-brand" href="#">LOGO</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                        <span class="navbar-toggler-icon"></span>
                                </button>
        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav mr-auto">
                                        <li class="nav-item active">
                                        <a class="nav-link" href="{% url 'saveNow:index' %}">Home <span class="sr-only">(current)</span></a>
                                        </li>
                                </ul>
                                        <center><ul class="navbar-nav mr-auto">            
                                                {% if user.is_authenticated %}
                                                        <li><form class="nav-item logout" action="{% url 'users:logout' %}" method="post">
                                                                {% csrf_token %}
                                                                <button type="submit">Logout</button>
                                                        </form></li>
                                                        <li class="nav-item create"><a class="nav-link" href="{% url 'saveNow:create' %}">Create Post</a></li>    
                                                {% else %}
                                                        <li class="nav-item signup"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                                                        <li class="nav-item"><a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a></li>
                                                {% endif %}
                                        </ul></center>
                        </div>
                        </nav>
                    </div> 
                </div>
                <div class="wrapper">
                        <div class="container">
                                <div class="col-md-12">
                                        {% for save in savepost %}
                                        <img src="{{save.thumb.url}}" alt="img of activity" width="1070" height="500">
                                        <h3>INFO</h3>
                                        <span class="lead">{{save.rank}}</span>
                                        <span class="lead">{{save.f_name}}</span>
                                        <span class="lead">{{save.l_name}}</span></br>
                                        <span class="lead">{{save.address}}</span>
                                        <span class="lead">{{save.date}}</span>
                                        {% endfor %}
                                </div>
                        </div>
                                <div class="col-md-12 copyright">
                                        &copy; Copyright All Rights Reserved SafeNow.com 2018-2020
                                </div>
                                
                </div>

</body>
</html>

saveNow/templates/saveNow/mainn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Save Now</title>
    <link rel="stylesheet" type="text/css" href="{% static 'saveNow/Bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'saveNow/styles.css' %}">
    
</head>
<body>
        <div class="row">
                <div class=nav>
                        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navpadding">
                                <a class="navbar-brand" href="#">LOGO</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                        <span class="navbar-toggler-icon"></span>
                                </button>
        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav mr-auto">
                                        <li class="nav-item active">
                                        <a class="nav-link" href="{% url 'saveNow:index' %}">Home <span class="sr-only">(current)</span></a>
                                        </li>
                                </ul>
                                        <center><ul class="navbar-nav mr-auto">            
                                                {% if user.is_authenticated %}
                                                        <li><form class="nav-item logout" action="{% url 'users:logout' %}" method="post">
                                                                {% csrf_token %}
                                                                <button type="submit">Logout</button>
                                                        </form></li>
                                                        <li class="nav-item create"><a class="nav-link" href="{% url 'saveNow:create' %}">Create Post</a></li>    
                                                {% else %}
                                                        <li class="nav-item signup"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                                                        <li class="nav-item"><a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a></li>
                                                {% endif %}
                                        </ul></center>
                        </div>
                        </nav>
                    </div> 
                </div>
{% block content %}
{% endblock %}

</body>
</html>

saveNow/templates/saveNow/savepost.html
{% extends 'saveNow/mainn.html' %}

{% block content %}
    <div class="container">
        <div class="row">
        <div class="col-md-4">
        <h2>Save a Life</h2>
        <form class="site-form" action="{% url 'saveNow:create' %} " method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="CREATE POST">
        </form>
        </div>
        <div class="col-md-4"></div>
        <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'saveNow/mainn.html' %}

{% block content %}
    <div class="div2">
        <p class="firstclass" align="center"><b>ADMIN LOGIN</b></p>
        <form name="myform" method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}
            {{form.username}}
            {{form.password}}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <input align = "center" type="submit" name = "submit" value="Login">
        </form>
    </div>
{% endblock %}

users/templates/users/signup.html
{% extends 'saveNow/mainn.html' %}

{% block content %}
<div class="div">
	<p class="firstclass" align="center"><b>CREATE AN ACCOUNT</b></p>
	<div class="container">
	<form name="myform" align="center" method="POST" action="{% url 'users:signup' %}">
		{% csrf_token %}
		<!-- {{form}} -->
		{{form.username}}
		{{form.f_name}}
		{{form.l_name}}
		{{form.email}}
		{{form.password1}}
		{{form.password2}}
	
		<input align="center" type="submit" value="Sign Up">
	</form>
	</div>
</div>
{% endblock %}